sudo: required
services:
  - docker

before_install:
  - docker build -t cyberdaemon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  cyberdaemon/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-308061541799"
  bucket_path: "docker-react"
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:  
  secure: "$AWS_SECRET_KEY"